function createfigure3(X1)
%CREATEFIGURE3(X1)
%  X1:  vector of x data
X1=1:25;
%  Auto-generated by MATLAB on 12-Jun-2019 19:55:08

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(6,5,1,'Parent',figure1);
hold(subplot1,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot1);

% Create ylabel
ylabel('puta');

box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'YMinorTick','on','YScale','log');
% Create subplot
subplot2 = subplot(6,5,2,'Parent',figure1);
hold(subplot2,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot2);

% Create ylabel
ylabel('puta');

box(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'YMinorTick','on','YScale','log');
% Create subplot
subplot3 = subplot(6,5,3,'Parent',figure1);
hold(subplot3,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot3);

% Create ylabel
ylabel('puta');

box(subplot3,'on');
% Set the remaining axes properties
set(subplot3,'YMinorTick','on','YScale','log');
% Create subplot
subplot4 = subplot(6,5,4,'Parent',figure1);
hold(subplot4,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot4);

% Create ylabel
ylabel('puta');

box(subplot4,'on');
% Set the remaining axes properties
set(subplot4,'YMinorTick','on','YScale','log');
% Create subplot
subplot5 = subplot(6,5,5,'Parent',figure1);
hold(subplot5,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot5);

% Create ylabel
ylabel('puta');

box(subplot5,'on');
% Set the remaining axes properties
set(subplot5,'YMinorTick','on','YScale','log');
% Create subplot
subplot6 = subplot(6,5,6,'Parent',figure1);
hold(subplot6,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot6);

% Create ylabel
ylabel('puta');

box(subplot6,'on');
% Set the remaining axes properties
set(subplot6,'YMinorTick','on','YScale','log');
% Create subplot
subplot7 = subplot(6,5,7,'Parent',figure1);
hold(subplot7,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot7);

% Create ylabel
ylabel('puta');

box(subplot7,'on');
% Set the remaining axes properties
set(subplot7,'YMinorTick','on','YScale','log');
% Create subplot
subplot8 = subplot(6,5,8,'Parent',figure1);
hold(subplot8,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot8);

% Create ylabel
ylabel('puta');

box(subplot8,'on');
% Set the remaining axes properties
set(subplot8,'YMinorTick','on','YScale','log');
% Create subplot
subplot9 = subplot(6,5,9,'Parent',figure1);
hold(subplot9,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot9);

% Create ylabel
ylabel('puta');

box(subplot9,'on');
% Set the remaining axes properties
set(subplot9,'YMinorTick','on','YScale','log');
% Create subplot
subplot10 = subplot(6,5,10,'Parent',figure1);
hold(subplot10,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot10);

% Create ylabel
ylabel('puta');

box(subplot10,'on');
% Set the remaining axes properties
set(subplot10,'YMinorTick','on','YScale','log');
% Create subplot
subplot11 = subplot(6,5,11,'Parent',figure1);
hold(subplot11,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot11);

% Create ylabel
ylabel('puta');

box(subplot11,'on');
% Set the remaining axes properties
set(subplot11,'YMinorTick','on','YScale','log');
% Create subplot
subplot12 = subplot(6,5,12,'Parent',figure1);
hold(subplot12,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot12);

% Create ylabel
ylabel('puta');

box(subplot12,'on');
% Set the remaining axes properties
set(subplot12,'YMinorTick','on','YScale','log');
% Create subplot
subplot13 = subplot(6,5,13,'Parent',figure1);
hold(subplot13,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot13);

% Create ylabel
ylabel('puta');

box(subplot13,'on');
% Set the remaining axes properties
set(subplot13,'YMinorTick','on','YScale','log');
% Create subplot
subplot14 = subplot(6,5,14,'Parent',figure1);
hold(subplot14,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot14);

% Create ylabel
ylabel('puta');

box(subplot14,'on');
% Set the remaining axes properties
set(subplot14,'YMinorTick','on','YScale','log');
% Create subplot
subplot15 = subplot(6,5,15,'Parent',figure1);
hold(subplot15,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot15);

% Create ylabel
ylabel('puta');

box(subplot15,'on');
% Set the remaining axes properties
set(subplot15,'YMinorTick','on','YScale','log');
% Create subplot
subplot16 = subplot(6,5,16,'Parent',figure1);
hold(subplot16,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot16);

% Create ylabel
ylabel('puta');

% Create xlabel
xlabel('puta');

box(subplot16,'on');
% Set the remaining axes properties
set(subplot16,'YMinorTick','on','YScale','log');
% Create subplot
subplot17 = subplot(6,5,17,'Parent',figure1);
hold(subplot17,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot17);

% Create ylabel
ylabel('puta');

box(subplot17,'on');
% Set the remaining axes properties
set(subplot17,'YMinorTick','on','YScale','log');
% Create subplot
subplot18 = subplot(6,5,18,'Parent',figure1);
hold(subplot18,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot18);

% Create ylabel
ylabel('puta');

box(subplot18,'on');
% Set the remaining axes properties
set(subplot18,'YMinorTick','on','YScale','log');
% Create subplot
subplot19 = subplot(6,5,19,'Parent',figure1);
hold(subplot19,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot19);

% Create ylabel
ylabel('puta');

box(subplot19,'on');
% Set the remaining axes properties
set(subplot19,'YMinorTick','on','YScale','log');
% Create subplot
subplot20 = subplot(6,5,20,'Parent',figure1);
hold(subplot20,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot20);

% Create ylabel
ylabel('puta');

box(subplot20,'on');
% Set the remaining axes properties
set(subplot20,'YMinorTick','on','YScale','log');
% Create subplot
subplot21 = subplot(6,5,21,'Parent',figure1);
hold(subplot21,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot21);

% Create ylabel
ylabel('puta');

box(subplot21,'on');
% Set the remaining axes properties
set(subplot21,'YMinorTick','on','YScale','log');
% Create subplot
subplot22 = subplot(6,5,22,'Parent',figure1);
hold(subplot22,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot22);

% Create ylabel
ylabel('puta');

box(subplot22,'on');
% Set the remaining axes properties
set(subplot22,'YMinorTick','on','YScale','log');
% Create subplot
subplot23 = subplot(6,5,23,'Parent',figure1);
hold(subplot23,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot23);

% Create ylabel
ylabel('puta');

box(subplot23,'on');
% Set the remaining axes properties
set(subplot23,'YMinorTick','on','YScale','log');
% Create subplot
subplot24 = subplot(6,5,24,'Parent',figure1);
hold(subplot24,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot24);

% Create ylabel
ylabel('puta');

box(subplot24,'on');
% Set the remaining axes properties
set(subplot24,'YMinorTick','on','YScale','log');
% Create subplot
subplot25 = subplot(6,5,25,'Parent',figure1);
hold(subplot25,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot25);

% Create ylabel
ylabel('puta');

box(subplot25,'on');
% Set the remaining axes properties
set(subplot25,'YMinorTick','on','YScale','log');
% Create subplot
subplot26 = subplot(6,5,26,'Parent',figure1);
hold(subplot26,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot26);

% Create ylabel
ylabel('puta');

box(subplot26,'on');
% Set the remaining axes properties
set(subplot26,'YMinorTick','on','YScale','log');
% Create subplot
subplot27 = subplot(6,5,27,'Parent',figure1);
hold(subplot27,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot27);

% Create ylabel
ylabel('puta');

box(subplot27,'on');
% Set the remaining axes properties
set(subplot27,'YMinorTick','on','YScale','log');
% Create subplot
subplot28 = subplot(6,5,28,'Parent',figure1);
hold(subplot28,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot28);

% Create ylabel
ylabel('puta');

box(subplot28,'on');
% Set the remaining axes properties
set(subplot28,'YMinorTick','on','YScale','log');
% Create subplot
subplot29 = subplot(6,5,29,'Parent',figure1);
hold(subplot29,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot29);

% Create ylabel
ylabel('puta');

box(subplot29,'on');
% Set the remaining axes properties
set(subplot29,'YMinorTick','on','YScale','log');
% Create subplot
subplot30 = subplot(6,5,30,'Parent',figure1);
hold(subplot30,'on');

% Create semilogy
semilogy(X1,X1,'Parent',subplot30);

% Create ylabel
ylabel('puta');

box(subplot30,'on');
% Set the remaining axes properties
set(subplot30,'YMinorTick','on','YScale','log');
