function createfigure1
%CREATEFIGURE1

%  Auto-generated by MATLAB on 12-Jun-2019 19:42:46

% Create figure
figure1 = figure;
subplot(6,5,1),plot(1:25,1:25)
% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.853002817525253 0.504847056936329 0.123739495798319 0.0971084378999597]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
% xlabel('Analysis Step');

% Set the remaining axes properties
set(axes1,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.201742313323573 0.504847056936329 0.12373949579832 0.0971084378999597]);

% Create ylabel
ylabel({'%Obs=0.7','','Norm error'});

% Create xlabel
% xlabel('Analysis Step');

% Set the remaining axes properties
set(axes2,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.201742313323573 0.803057125013947 0.12373949579832 0.0971084378999593]);

% Create ylabel
ylabel({'%Obs=0.7','','Norm error'});

% Create xlabel
xlabel('Analysis Step');

% Create title
title({''});

% Set the remaining axes properties
set(axes3,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes4 = axes('Parent',figure1,...
    'Position',[0.364557439373993 0.803057125013947 0.123739495798319 0.0971084378999593]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes4,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes5 = axes('Parent',figure1,...
    'Position',[0.527372565424413 0.803057125013947 0.123739495798319 0.0971084378999593]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes5,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes6 = axes('Parent',figure1,...
    'Position',[0.690187691474834 0.803057125013947 0.123739495798319 0.0971084378999593]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes6,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes7 = axes('Parent',figure1,...
    'Position',[0.853002817525253 0.803057125013947 0.123739495798319 0.0971084378999593]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes7,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes8 = axes('Parent',figure1,...
    'Position',[0.201742313323573 0.650640832696992 0.12373949579832 0.0971084378999595]);

% Create ylabel
ylabel({'%Obs=1','','Norm error'});

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes8,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes9 = axes('Parent',figure1,...
    'Position',[0.364557439373993 0.650640832696992 0.123739495798319 0.0971084378999595]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes9,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes10 = axes('Parent',figure1,...
    'Position',[0.527372565424413 0.650640832696992 0.123739495798319 0.0971084378999595]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes10,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes11 = axes('Parent',figure1,...
    'Position',[0.690187691474834 0.650640832696992 0.123739495798319 0.0971084378999595]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes11,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes12 = axes('Parent',figure1,...
    'Position',[0.853002817525253 0.650640832696992 0.123739495798319 0.0971084378999595]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes12,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes13 = axes('Parent',figure1,...
    'Position',[0.364557439373993 0.504847056936329 0.123739495798319 0.0971084378999597]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes13,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes14 = axes('Parent',figure1,...
    'Position',[0.527372565424413 0.504847056936329 0.123739495798319 0.0971084378999597]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes14,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes15 = axes('Parent',figure1,...
    'Position',[0.690187691474834 0.504847056936329 0.123739495798319 0.0971084378999597]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes15,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes16 = axes('Parent',figure1,...
    'Position',[0.201742313323573 0.357397652036594 0.12373949579832 0.0971084378999595]);

% Create ylabel
ylabel({'%Obs=1','','Norm error'});

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes16,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes17 = axes('Parent',figure1,...
    'Position',[0.364557439373993 0.357397652036594 0.123739495798319 0.0971084378999595]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes17,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes18 = axes('Parent',figure1,...
    'Position',[0.527372565424413 0.357397652036594 0.123739495798319 0.0971084378999595]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes18,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes19 = axes('Parent',figure1,...
    'Position',[0.690187691474834 0.357397652036594 0.123739495798319 0.0971084378999595]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes19,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes20 = axes('Parent',figure1,...
    'Position',[0.853002817525253 0.357397652036594 0.123739495798319 0.0971084378999595]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes20,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes21 = axes('Parent',figure1,...
    'Position',[0.201742313323573 0.211603876275931 0.12373949579832 0.0971084378999597]);

% Create ylabel
ylabel({'%Obs=0.7','','Norm error'});

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes21,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes22 = axes('Parent',figure1,...
    'Position',[0.364557439373993 0.211603876275931 0.123739495798319 0.0971084378999597]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes22,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes23 = axes('Parent',figure1,...
    'Position',[0.527372565424413 0.211603876275931 0.123739495798319 0.0971084378999597]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes23,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes24 = axes('Parent',figure1,...
    'Position',[0.690187691474834 0.211603876275931 0.123739495798319 0.0971084378999597]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes24,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes25 = axes('Parent',figure1,...
    'Position',[0.853002817525253 0.211603876275931 0.123739495798319 0.0971084378999597]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes25,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes26 = axes('Parent',figure1,...
    'Position',[0.201742313323573 0.0575319548199034 0.12373949579832 0.0971084378999596]);

% Create ylabel
ylabel({'%Obs=1','','Norm error'});

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes26,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes27 = axes('Parent',figure1,...
    'Position',[0.364557439373993 0.0575319548199034 0.123739495798319 0.0971084378999596]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes27,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes28 = axes('Parent',figure1,...
    'Position',[0.527372565424413 0.0575319548199034 0.123739495798319 0.0971084378999596]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes28,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes29 = axes('Parent',figure1,...
    'Position',[0.690187691474834 0.0575319548199034 0.123739495798319 0.0971084378999596]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes29,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
axes30 = axes('Parent',figure1,...
    'Position',[0.853002817525253 0.0575319548199034 0.123739495798319 0.0971084378999596]);

% Create ylabel
ylabel('Norm Error');

% Create xlabel
xlabel('Analysis Step');

% Set the remaining axes properties
set(axes30,'FontSize',8,'YMinorTick','on','YScale','log');
% Create textbox
annotation(figure1,'textbox',...
    [0.0322108345534407 0.449331127012013 0.053074669207434 0.0562913895442786],...
    'String',{'N=40'},...
    'LineStyle','none',...
    'FontSize',14,...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',...
    [0.0292825768667643 0.765556292574927 0.053074669207434 0.0562913895442786],...
    'String',{'N=20'},...
    'LineStyle','none',...
    'FontSize',14,...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',...
    [0.454612005856516 0.944364239989526 0.113103949995289 0.0695364222621286],...
    'String',{'r=5 and F_{obs}=1'},...
    'LineStyle','none',...
    'FontSize',14,...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',...
    [0.244509516837482 0.898006623700755 0.0428257676095076 0.0562913895442786],...
    'String',{'\gamma=1'},...
    'LineStyle','none',...
    'FontSize',14,...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',...
    [0.4099560761347 0.898006623700755 0.0428257676095076 0.0562913895442786],...
    'String',{'\gamma=2'},...
    'LineStyle','none',...
    'FontSize',14,...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',...
    [0.567349926793558 0.898006623700755 0.0428257676095076 0.0562913895442786],...
    'String',{'\gamma=3'},...
    'LineStyle','none',...
    'FontSize',14,...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',...
    [0.731332357247438 0.898006623700755 0.0428257676095076 0.0562913895442786],...
    'String',{'\gamma=4'},...
    'LineStyle','none',...
    'FontSize',14,...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',...
    [0.904099560761347 0.898006623700755 0.0428257676095076 0.0562913895442786],...
    'String',{'\gamma=5'},...
    'LineStyle','none',...
    'FontSize',14,...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',...
    [0.034407027818448 0.149662252839828 0.053074669207434 0.0562913895442786],...
    'String',{'N=80'},...
    'LineStyle','none',...
    'FontSize',14,...
    'FitBoxToText','off');

% Create rectangle
annotation(figure1,'rectangle',...
    [0.09370424597365 0.0149006622516556 0.894582723279659 0.307947019867549],...
    'LineStyle','-.');

% Create rectangle
annotation(figure1,'rectangle',...
    [0.09370424597365 0.327814569536424 0.894582723279659 0.288079470198675],...
    'LineStyle','-.');

% Create rectangle
annotation(figure1,'rectangle',...
    [0.0944363103953148 0.620517593920713 0.894582723279657 0.32615894039735],...
    'LineStyle','-.');

