function createfigure(figura,X1,Y1,X2,Y2,X3,Y3,X4,Y4,X5,Y5,X6,Y6,X7,Y7,X8,Y8,X9,Y9,X10,Y10,X11,Y11,X12,Y12,X13,Y13,X14,Y14,X15,Y15,X16,Y16,X17,Y17,X18,Y18,X19,Y19,X20,Y20,X21,Y21,X22,Y22,X23,Y23,X24,Y24,X25,Y25,X26,Y26,X27,Y27,X28,Y28,X29,Y29,X30,Y30)
%CREATEFIGURE

%  Auto-generated by MATLAB on 12-Jun-2019 19:37:38
% Create figure
figure1 = figure(figura);

% Create axes
subplot1 = subplot(6,5,1,'Parent',figure1,'Position',[0.853002817525253 0.504847056936329 0.123739495798319 0.0971084378999597]);
hold(subplot1,'on');
for i=1:size(Y15,1)
semilogy(X15(i,:),Y15(i,:),'Parent',subplot1);
end
%axes1 = axes('Parent',figure1,...
%     'Position',[0.853002817525253 0.504847056936329 0.123739495798319 0.0971084378999597]);

% Create ylabel
ylabel('X15');

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 100000]);
% Set the remaining axes properties
set(subplot1,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
% 
 subplot2 = subplot(6,5,2,'Parent',figure1,'Position',[0.201742313323573 0.504847056936329 0.12373949579832 0.0971084378999597]);
 hold(subplot2,'on');
 for i=1:size(Y11,1)
 semilogy(X11(i,:),Y11(i,:),'Parent',subplot2);
 end
% % Create ylabel
 ylabel({'x11'});
% 
% % Create xlabel
 
% 
% % Uncomment the following line to preserve the X-limits of the axes
% % xlim(axes2,[0 25]);
% % Uncomment the following line to preserve the Y-limits of the axes
% % ylim(axes2,[0 100000]);
% % Set the remaining axes properties
 set(subplot2,'FontSize',8,'YMinorTick','on','YScale','log');
% % Create axes



% Create axes
 subplot5 = subplot(6,5,1,'Parent',figure1,'Position',[0.527372565424413 0.803057125013947 0.123739495798319 0.0971084378999593]);
 hold(subplot5,'on');
% 
 for i=1:size(Y3,1)
 semilogy(X3(i,:),Y3(i,:),'Parent',subplot5);
 end
% 
% % Create ylabel
 ylabel('x3');
% 
% % Create xlabel
 

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes5,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes5,[0 100000]);
% Set the remaining axes properties
 set(subplot5,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot6 = subplot(6,5,2,'Parent',figure1,'Position',[0.690187691474834 0.803057125013947 0.123739495798319 0.0971084378999593]);
hold(subplot6,'on');

for i=1:size(Y4,1)
semilogy(X4(i,:),Y4(i,:),'Parent',subplot6);
end
% Create ylabel
ylabel('x4');

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes6,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes6,[0 100000]);
% Set the remaining axes properties
set(subplot6,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot7 = subplot(6,5,2,'Parent',figure1,'Position',[0.853002817525253 0.803057125013947 0.123739495798319 0.0971084378999593]);
hold(subplot7,'on');

for i=1:size(Y5,1)
semilogy(X5(i,:),Y5(i,:),'Parent',subplot7);
end
% Create ylabel
ylabel('x5');

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes7,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes7,[0 100000]);
% Set the remaining axes properties
set(subplot7,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes

subplot8 = subplot(6,5,2,'Parent',figure1,'Position',[0.201742313323573 0.650640832696992 0.12373949579832 0.0971084378999595]);
hold(subplot8,'on');

for i=1:size(Y6,1)
semilogy(X6(i,:),Y6(i,:),'Parent',subplot8);
end
% Create ylabel
ylabel({'x6'});

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes8,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes8,[0 100000]);
% Set the remaining axes properties
set(subplot8,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes

subplot9 = subplot(6,5,2,'Parent',figure1,'Position',[0.364557439373993 0.650640832696992 0.123739495798319 0.0971084378999595]);
hold(subplot9,'on');

for i=1:size(Y7,1)
semilogy(X7(i,:),Y7(i,:),'Parent',subplot9);
end
% Create ylabel
ylabel('x7');

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes9,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes9,[0 100000]);
% Set the remaining axes properties
set(subplot9,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot10 = subplot(6,5,2,'Parent',figure1,'Position',[0.527372565424413 0.650640832696992 0.123739495798319 0.0971084378999595]);
hold(subplot10,'on');

for i=1:size(Y8,1)
semilogy(X8(i,:),Y8(i,:),'Parent',subplot10);
end
% Create ylabel
ylabel('x8');

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes10,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes10,[0 100000]);
% Set the remaining axes properties
set(subplot10,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot11 = subplot(6,5,2,'Parent',figure1,'Position',[0.690187691474834 0.650640832696992 0.123739495798319 0.0971084378999595]);
hold(subplot11,'on');

for i=1:size(Y9,1)
semilogy(X9(i,:),Y9(i,:),'Parent',subplot11);
end
% Create ylabel
ylabel('x9');

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes11,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes11,[0 100000]);
% Set the remaining axes properties
set(subplot11,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot12 = subplot(6,5,2,'Parent',figure1,'Position',[0.853002817525253 0.650640832696992 0.123739495798319 0.0971084378999595]);
hold(subplot12,'on');

for i=1:size(Y10,1)
semilogy(X10(i,:),Y10(i,:),'Parent',subplot12);
end
% Create ylabel
ylabel('x10');

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes12,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes12,[0 100000]);
% Set the remaining axes properties
set(subplot12,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot13 = subplot(6,5,2,'Parent',figure1,'Position',[0.364557439373993 0.504847056936329 0.123739495798319 0.0971084378999597]);
hold(subplot13,'on');

for i=1:size(Y12,1)
semilogy(X12(i,:),Y12(i,:),'Parent',subplot13);
end

% Create ylabel
ylabel('x12');

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes13,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes13,[0 100000]);
% Set the remaining axes properties
set(subplot13,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot14 = subplot(6,5,2,'Parent',figure1,'Position',[0.527372565424413 0.504847056936329 0.123739495798319 0.0971084378999597]);
hold(subplot14,'on');
for i=1:size(Y13,1)
semilogy(X13(i,:),Y13(i,:),'Parent',subplot14);
end
% Create ylabel
ylabel('x13');

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes14,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes14,[0 100000]);
% Set the remaining axes properties
set(subplot14,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot15 = subplot(6,5,2,'Parent',figure1,'Position',[0.690187691474834 0.504847056936329 0.123739495798319 0.0971084378999597]);
hold(subplot15,'on');
for i=1:size(Y14,1)
semilogy(X14(i,:),Y14(i,:),'Parent',subplot15);
end

% Create ylabel
ylabel('x14');

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes15,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes15,[0 100000]);
% Set the remaining axes properties
set(subplot15,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes

subplot16 = subplot(6,5,2,'Parent',figure1,'Position',[0.201742313323573 0.357397652036594 0.123739495798319 0.0971084378999597]);
hold(subplot16,'on');
for i=1:size(Y16,1)
semilogy(X16(i,:),Y16(i,:),'Parent',subplot16);
end
% Create ylabel
ylabel({'x16'});

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes16,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes16,[0 100000]);
% Set the remaining axes properties
set(subplot16,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot17 = subplot(6,5,2,'Parent',figure1,'Position',[0.364557439373993 0.357397652036594 0.123739495798319 0.0971084378999595]);
hold(subplot17,'on');
for i=1:size(Y17,1)
semilogy(X17(i,:),Y17(i,:),'Parent',subplot17);
end
% Create ylabel
ylabel('x17');

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes17,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes17,[0 100000]);
% Set the remaining axes properties
set(subplot17,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot18 = subplot(6,5,2,'Parent',figure1,'Position',[0.527372565424413 0.357397652036594 0.123739495798319 0.0971084378999595]);
hold(subplot18,'on');
for i=1:size(Y18,1)
semilogy(X18(i,:),Y18(i,:),'Parent',subplot18);
end

% Create ylabel
ylabel('x18');

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes18,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes18,[0 100000]);
% Set the remaining axes properties
set(subplot18,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot19 = subplot(6,5,2,'Parent',figure1,'Position',[0.690187691474834 0.357397652036594 0.123739495798319 0.0971084378999595]);
hold(subplot19,'on');
for i=1:size(Y19,1)
semilogy(X19(i,:),Y19(i,:),'Parent',subplot19);
end

% Create ylabel
ylabel('x19');
% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes19,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes19,[0 100000]);
% Set the remaining axes properties
set(subplot19,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot20 = subplot(6,5,2,'Parent',figure1,'Position',[0.853002817525253 0.357397652036594 0.123739495798319 0.0971084378999595]);
hold(subplot20,'on');
for i=1:size(Y20,1)
semilogy(X20(i,:),Y20(i,:),'Parent',subplot20);
end

% Create ylabel
ylabel('x20');

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes20,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes20,[0 100000]);
% Set the remaining axes properties
set(subplot20,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot21 = subplot(6,5,2,'Parent',figure1,'Position',[0.201742313323573 0.211603876275931 0.12373949579832 0.0971084378999597]);
hold(subplot21,'on');
for i=1:size(Y21,1)
semilogy(X21(i,:),Y21(i,:),'Parent',subplot21);
end

% Create ylabel
ylabel('x21');

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes21,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes21,[0 100000]);
% Set the remaining axes properties
set(subplot21,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes

subplot22 = subplot(6,5,2,'Parent',figure1,'Position',[0.364557439373993 0.211603876275931 0.123739495798319 0.0971084378999597]);
hold(subplot22,'on');
for i=1:size(Y22,1)
semilogy(X22(i,:),Y22(i,:),'Parent',subplot22);
end

% Create ylabel
ylabel('x22');% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes22,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes22,[0 100000]);
% Set the remaining axes properties
set(subplot22,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot23 = subplot(6,5,2,'Parent',figure1,'Position',[0.527372565424413 0.211603876275931 0.123739495798319 0.0971084378999597]);
hold(subplot23,'on');
for i=1:size(Y23,1)
semilogy(X23(i,:),Y23(i,:),'Parent',subplot23);
end

% Create ylabel
ylabel('x23');% Create xlabel

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes23,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes23,[0 100000]);
% Set the remaining axes properties
set(subplot23,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot24 = subplot(6,5,2,'Parent',figure1,'Position',[0.690187691474834 0.211603876275931 0.123739495798319 0.0971084378999597]);
hold(subplot24,'on');
for i=1:size(Y24,1)
semilogy(X24(i,:),Y24(i,:),'Parent',subplot24);
end

% Create ylabel
ylabel('x24');% Create xlabel


% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes24,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes24,[0 100000]);
% Set the remaining axes properties
set(subplot24,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot25 = subplot(6,5,2,'Parent',figure1,'Position',[0.853002817525253 0.211603876275931 0.123739495798319 0.0971084378999597]);
hold(subplot25,'on');
for i=1:size(Y25,1)
semilogy(X25(i,:),Y25(i,:),'Parent',subplot25);
end

% Create ylabel
ylabel('x25');% Create xlabel

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes25,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes25,[0 100000]);
% Set the remaining axes properties
set(subplot25,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot26 = subplot(6,5,2,'Parent',figure1,'Position',[0.201742313323573 0.0575319548199034 0.12373949579832 0.0971084378999596]);
hold(subplot26,'on');
for i=1:size(Y26,1)
semilogy(X26(i,:),Y26(i,:),'Parent',subplot26);
end

% Create ylabel
ylabel('x26');% Create xlabel

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes26,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes26,[0 100000]);
% Set the remaining axes properties
set(subplot26,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot27 = subplot(6,5,2,'Parent',figure1,'Position',[0.364557439373993 0.0575319548199034 0.123739495798319 0.0971084378999596]);
hold(subplot27,'on');
for i=1:size(Y27,1)
semilogy(X27(i,:),Y27(i,:),'Parent',subplot27);
end

% Create ylabel
ylabel('x27');% Create xlabel

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes27,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes27,[0 100000]);
% Set the remaining axes properties
set(subplot27,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot28 = subplot(6,5,2,'Parent',figure1,'Position',[0.527372565424413 0.0575319548199034 0.123739495798319 0.0971084378999596]);
hold(subplot28,'on');
for i=1:size(Y28,1)
semilogy(X28(i,:),Y28(i,:),'Parent',subplot28);
end

% Create ylabel
ylabel('x28');% Create xlabel

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes28,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes28,[0 100000]);
% Set the remaining axes properties
set(subplot28,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot29 = subplot(6,5,2,'Parent',figure1,'Position',[0.690187691474834 0.0575319548199034 0.123739495798319 0.0971084378999596]);
hold(subplot29,'on');
for i=1:size(Y29,1)
semilogy(X29(i,:),Y29(i,:),'Parent',subplot29);
end

% Create ylabel
ylabel('x29');% Create xlabel

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes29,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes29,[0 100000]);
% Set the remaining axes properties
set(subplot29,'FontSize',8,'YMinorTick','on','YScale','log');
% Create axes
subplot30 = subplot(6,5,2,'Parent',figure1,'Position',[0.853002817525253 0.0575319548199034 0.123739495798319 0.0971084378999596]);
hold(subplot30,'on');
for i=1:size(Y30,1)
semilogy(X30(i,:),Y30(i,:),'Parent',subplot30);
end

% Create ylabel
ylabel('x30');% Create xlabel
% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes30,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes30,[0 100000]);
% Set the remaining axes properties
set(subplot30,'FontSize',8,'YMinorTick','on','YScale','log');
% Create textbox
% Create axes
 subplot4 = subplot(6,5,2,'Parent',figure1,'Position',[0.364557439373993 0.803057125013947 0.123739495798319 0.0971084378999593]);
hold(subplot4,'on');

for i=1:size(Y2,1)
semilogy(X2(i,:),Y2(i,:),'Parent',subplot4);
end
% Create ylabel
ylabel('x2');

% Create xlabel


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[0 100000]);
% Set the remaining axes properties
set(subplot4,'FontSize',8,'YMinorTick','on','YScale','log');

subplot3 = subplot(6,5,1,'Parent',figure1,'Position',[0.201742313323573 0.803057125013947 0.12373949579832 0.0971084378999593]);
hold(subplot3,'on');

for i=1:size(Y1,1)
semilogy(X1(i,:),Y1(i,:),'Parent',subplot3);
end
% Create ylabel
ylabel({'x1'});

% Create xlabel


% Create title
title({''});

% % Set the remaining axes properties
 set(subplot3,'FontSize',8,'YMinorTick','on','YScale','log');
annotation(figure1,'textbox',...
    [0.0322108345534407 0.449331127012013 0.053074669207434 0.0562913895442786],...
    'String',{'N=40'},...
    'LineStyle','none',...
    'FontSize',14);

% Create textbox
annotation(figure1,'textbox',...
    [0.0292825768667643 0.765556292574927 0.053074669207434 0.0562913895442786],...
    'String',{'N=20'},...
    'LineStyle','none',...
    'FontSize',14);

% Create textbox
annotation(figure1,'textbox',...
    [0.454612005856516 0.944364239989526 0.113103949995289 0.0695364222621286],...
    'String',{'r=5 and F_{obs}=1'},...
    'LineStyle','none',...
    'FontSize',14);

% Create textbox
annotation(figure1,'textbox',...
    [0.244509516837482 0.898006623700755 0.0428257676095076 0.0562913895442786],...
    'String',{'\gamma=1'},...
    'LineStyle','none',...
    'FontSize',14);

% Create textbox
annotation(figure1,'textbox',...
    [0.4099560761347 0.898006623700755 0.0428257676095076 0.0562913895442786],...
    'String',{'\gamma=2'},...
    'LineStyle','none',...
    'FontSize',14);

% Create textbox
annotation(figure1,'textbox',...
    [0.567349926793558 0.898006623700755 0.0428257676095076 0.0562913895442786],...
    'String',{'\gamma=3'},...
    'LineStyle','none',...
    'FontSize',14);

% Create textbox
annotation(figure1,'textbox',...
    [0.731332357247438 0.898006623700755 0.0428257676095076 0.0562913895442786],...
    'String',{'\gamma=4'},...
    'LineStyle','none',...
    'FontSize',14);

% Create textbox
annotation(figure1,'textbox',...
    [0.904099560761347 0.898006623700755 0.0428257676095076 0.0562913895442786],...
    'String',{'\gamma=5'},...
    'LineStyle','none',...
    'FontSize',14);

% Create textbox
annotation(figure1,'textbox',...
    [0.034407027818448 0.149662252839828 0.053074669207434 0.0562913895442786],...
    'String',{'N=80'},...
    'LineStyle','none',...
    'FontSize',14);

% Create rectangle
annotation(figure1,'rectangle',...
    [0.0937042459736457 0.620860927152317 0.894582723279657 0.326158940397351],...
    'LineStyle','-.');

% Create rectangle
annotation(figure1,'rectangle',...
    [0.09370424597365 0.0149006622516556 0.894582723279659 0.307947019867549],...
    'LineStyle','-.');

% Create rectangle
annotation(figure1,'rectangle',...
    [0.09370424597365 0.327814569536424 0.894582723279659 0.288079470198675],...
    'LineStyle','-.');

